#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: '{branch}-{build}'

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x64

# set clone depth
clone_depth: 1

# clone directory
clone_folder: c:\projects\panda3d

# scripts that are called at very beginning, before repo cloning
init:
- ps: >-
    if (Test-Path env:TRIGGER_NAME) {
        Update-AppveyorBuild -Message "Build from $env:TRIGGER_COMMIT in $env:TRIGGER_NAME"
    } else {
        Set-AppveyorBuildVariable -Name 'TRIGGER_NAME' -Value "$env:APPVEYOR_PROJECT_NAME"
        Set-AppveyorBuildVariable -Name 'TRIGGER_COMMIT' -Value "$env:APPVEYOR_REPO_COMMIT".substring(0, 8)
    }
- ps: git --version
- ps: python --version
- ps: cmake --version

# environment variables
environment:
    CMAKE_PREFIX_PATH: C:\projects\_install;C:\projects\_cache;
    MAKEPANDA_THIRDPARTY: C:/projects/_install/panda3d-thirdparty
    PATH: C:\Python36-x64;%PATH%

# scripts that run after cloning repository
install:
- ps: (mkdir C:\projects\_install) -and (pushd C:\projects\_install)
- ps: Start-FileDownload 'https://ci.appveyor.com/api/projects/bluekyu/panda3d-thirdparty/artifacts/panda3d-thirdparty.zip?branch=develop'
- ps: 7z x panda3d-thirdparty.zip -opanda3d-thirdparty
- ps: popd

# build cache to preserve files/folders between builds
cache:
    - C:\projects\_cache

#---------------------------------#
#       build configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic MSBuild
build_script:
- ps: (mkdir _build) -and (pushd _build)
- cmd: >-
    cmake -G "Visual Studio 15 2017 Win64" -Wno-dev
    -DCMAKE_INSTALL_PREFIX="C:/projects/panda3d/_artifacts"
    ..
- cmd: cmake --build . --config "Release" --target INSTALL
- ps: popd

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to disable automatic tests
test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
- path: _artifacts
  name: panda3d

#---------------------------------#
#        global handlers          #
#---------------------------------#

# on successful build
on_success:
- ps: >-
    Start-AppveyorBuild -ApiKey $env:api_key -ProjectSlug 'render-pipeline-cpp' -EnvironmentVariables @{
        TRIGGER_NAME = $env:TRIGGER_NAME
        TRIGGER_COMMIT = $env:TRIGGER_COMMIT
    }
