language: cpp

sudo: false

# blocklist
branches:
    except:
    - master

matrix:
    include:
        - compiler: clang
          env: >
            INSTALL_DIR=~/_install
            CACHE_DIR=~/_cache
            CONFIGURATION=Release

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libfreetype6-dev
        - libgl1-mesa-dev
        - libjpeg-dev
        - libopenal-dev
        - libpng-dev
        - libvorbis-dev
        - libxrandr-dev
        - python3-dev
        - zlib1g-dev

cache:
    directories:
    - $CACHE_DIR

before_install:
- if [ ! -d "$INSTALL_DIR" ]; then mkdir "$INSTALL_DIR"; fi

install:
- if [ ! -d "$CACHE_DIR" ]; then mkdir "$CACHE_DIR"; fi
- >
    if [ ! -d "$CACHE_DIR/cmake" ]; then
        wget https://cmake.org/files/v3.9/cmake-3.9.1-Linux-x86_64.tar.gz;
        tar xvf cmake-3.9.1-Linux-x86_64.tar.gz;
        mv cmake-3.9.1-Linux-x86_64 "$CACHE_DIR/cmake";
    fi

before_script:
- export PATH=$CACHE_DIR/cmake/bin:$PATH
- git --version
- python --version
- cmake --version

script:
- mkdir _build && pushd _build
- >
    cmake -Wno-dev ..
    -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR
- cmake --build . --config $CONFIGURATION --target install
- ctest --output-on-failure
- popd

notifications:
    email:
        on_success: never
