#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: '{branch}-{build}'

# branches to build
branches:
  only:
  - develop

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
- cmd: >-
    git --version

    cmake --version

    set PATH=C:\Python36-x64;%PATH%


# environment variables
environment:
  CMAKE_GENERATOR: Visual Studio 15 2017 Win64

# build cache to preserve files/folders between builds
cache:
    - C:\projects\_install -> appveyor.yml

# scripts that run after cloning repository
install:
    - git clone https://github.com/bluekyu/render_pipeline_cpp_ci.git c:\projects\render_pipeline_cpp_ci
    - mklink /J c:\projects\render_pipeline_cpp_ci\panda3d C:\projects\panda3d

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x64

# to run your custom scripts instead of automatic MSBuild
build_script:
- cmd: >-
    cd c:\projects\render_pipeline_cpp_ci

    python build.py panda3d --cmake-generator "%CMAKE_GENERATOR%" --install-prefix="C:/projects/_install"
