#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - git clone https://github.com/bluekyu/render_pipeline_cpp_ci c:\projects\render_pipeline_cpp_ci

# clone directory
clone_folder: c:\projects\render_pipeline_cpp_ci\panda3d

# environment variables
environment:
  CMAKE_GENERATOR: Visual Studio 15 2017 Win64

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - cmake --version
  - cd c:\projects\render_pipeline_cpp_ci
  - mkdir _build && cd _build
  - cmake -G "%CMAKE_GENERATOR%" -DCMAKE_INSTALL_PREFIX=%CD:\=/%/install -DCMAKE_BUILD_TYPE=Release -Dpanda3d_MANUAL_GIT:BOOL=ON ..
  - cmake --build . --config Release --target ALL_BUILD
