variables:
  REPO_NAME: 'panda3d'
  BUILD_PATH: '$(Build.SourcesDirectory)/build'

jobs:
- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'

  strategy:
    matrix:
      vc140-release:
        BUILD_TOOLSET_VERSION: '140'
        BUILD_CONFIGURATION: 'release'
        PANDA_BUILD_OPTIMIZE: '4'
      vc141-debug:
        BUILD_TOOLSET_VERSION: '141'
        BUILD_CONFIGURATION: 'debug'
        PANDA_BUILD_OPTIMIZE: '1'
      vc141-release:
        BUILD_TOOLSET_VERSION: '141'
        BUILD_CONFIGURATION: 'release'
        PANDA_BUILD_OPTIMIZE: '4'

  variables:
    CMAKE_GENERATOR: 'Visual Studio 15 2017 Win64'
    MAKEPANDA_THIRDPARTY: '$(BUILD_PATH)/panda3d-thirdparty'

  steps:
  # initialize
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      addToPath: true
      architecture: 'x64'

  # download artifacts
  - task: DownloadBuildArtifacts@0
    displayName: Download panda3d-thirdparty
    inputs:
      buildType: 'specific'
      project: rpcpp-devops
      pipeline: panda3d-thirdparty
      specificBuildWithTriggering: true
      downloadType: 'single'
      artifactName: 'panda3d-thirdparty-vc$(BUILD_TOOLSET_VERSION)-$(BUILD_CONFIGURATION)'
      downloadPath: '$(BUILD_PATH)'

  # extract artifacts
  - task: ExtractFiles@1
    displayName: Extract panda3d-thirdparty
    inputs:
      archiveFilePatterns: '$(BUILD_PATH)/panda3d-thirdparty-vc$(BUILD_TOOLSET_VERSION)-$(BUILD_CONFIGURATION)/panda3d-thirdparty.7z'
      destinationFolder: '$(BUILD_PATH)'
      cleanDestinationFolder: false

  # configure & generate
  - task: CMake@1
    displayName: CMake Generate
    inputs:
      cmakeArgs: .. -G "$(CMAKE_GENERATOR)" -Wno-dev -T "v$(BUILD_TOOLSET_VERSION),host=x64" -DCMAKE_INSTALL_PREFIX="$(Build.BinariesDirectory)/$(REPO_NAME)" -Dpanda3d_build_eigen=OFF -Dpanda3d_build_optimize=$(PANDA_BUILD_OPTIMIZE)

  # build
  - task: CMake@1
    displayName: CMake Build
    inputs:
      cmakeArgs: --build . --config $(BUILD_CONFIGURATION)

  # tests
  - script: ctest -C $(BUILD_CONFIGURATION) --output-on-failure
    displayName: CTest
    workingDirectory: '$(Build.SourcesDirectory)/build'

  # install
  - task: CMake@1
    displayName: CMake Install
    inputs:
      cmakeArgs: --build . --config $(BUILD_CONFIGURATION) --target install

  # packaging
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.BinariesDirectory)/$(REPO_NAME)'
      archiveType: '7z'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(REPO_NAME).7z'

  # publish
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: '$(REPO_NAME)-vc$(BUILD_TOOLSET_VERSION)-$(BUILD_CONFIGURATION)'
